# Generated by Django 5.2.5 on 2026-09-06 11:12

from django.db import migrations, models


def create_site_content(apps, schema_editor):
    SiteContent = apps.get_model("portfolio", "SiteContent")
    SiteContent.objects.get_or_create(pk=1)


def remove_site_content(apps, schema_editor):
    SiteContent = apps.get_model("portfolio", "SiteContent")
    SiteContent.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_workproject_youtube'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='VOX — Video Editor & Motion Designer', max_length=180, verbose_name='Browser title')),
                ('meta_description', models.TextField(default='VOX — video editor and motion designer turning information into attention.', max_length=320, verbose_name='Search description')),
                ('skip_link_label', models.CharField(default='Skip to content', max_length=80)),
                ('brand_name', models.CharField(default='VOX', max_length=40)),
                ('menu_open_label', models.CharField(default='MENU', max_length=40)),
                ('menu_close_label', models.CharField(default='CLOSE', max_length=40)),
                ('nav_work', models.CharField(default='WORK', max_length=40)),
                ('nav_services', models.CharField(default='SERVICES', max_length=40)),
                ('nav_about', models.CharField(default='ABOUT', max_length=40)),
                ('nav_process', models.CharField(default='PROCESS', max_length=40)),
                ('nav_contact', models.CharField(default='CONTACT', max_length=40)),
                ('header_cta', models.CharField(default="LET'S TALK", max_length=60)),
                ('hero_index', models.CharField(default='01 / EDITORIAL MOTION', max_length=80)),
                ('hero_line_1', models.CharField(default='TURNING', max_length=80)),
                ('hero_line_2', models.CharField(default='INFORMATION', max_length=80)),
                ('hero_line_3', models.CharField(default='INTO', max_length=80)),
                ('hero_line_4', models.CharField(default='ATTENTION', max_length=80)),
                ('hero_intro', models.TextField(default='I create videos and motion design that make complex ideas clear, engaging, and impossible to ignore.', max_length=400)),
                ('hero_cta', models.CharField(default='VIEW MY WORK', max_length=60)),
                ('hero_image_alt', models.CharField(default='Young video editor standing with folded arms', max_length=180)),
                ('hero_role', models.CharField(default='VIDEO EDITOR &\nMOTION DESIGNER', max_length=120)),
                ('hero_attention', models.CharField(default='ATTENTION', max_length=60)),
                ('services_heading', models.TextField(default='I HELP BRANDS, CREATORS,\nAND COMPANIES TURN INFORMATION\nINTO CONTENT THAT', max_length=320)),
                ('services_highlight', models.CharField(default='GETS ATTENTION.', max_length=100)),
                ('service_1_title', models.CharField(default='VIDEO EDITING', max_length=80)),
                ('service_1_description', models.TextField(default='Clean cuts. Strong pacing.\nStories that flow.', max_length=240)),
                ('service_2_title', models.CharField(default='MOTION DESIGN', max_length=80)),
                ('service_2_description', models.TextField(default='Bringing ideas to life\nwith purpose and style.', max_length=240)),
                ('service_3_title', models.CharField(default='STORYTELLING', max_length=80)),
                ('service_3_description', models.TextField(default='Turning complex information\ninto clear, engaging stories.', max_length=240)),
                ('work_index', models.CharField(default='02 / SELECTED PROJECTS', max_length=80)),
                ('work_title_1', models.CharField(default='WORK THAT', max_length=80)),
                ('work_title_2', models.CharField(default='MAKES NOISE.', max_length=80)),
                ('work_intro', models.TextField(default='A selection of editorial films, explainers, campaigns, and motion systems made to be watched—not skipped.', max_length=400)),
                ('work_format_label', models.CharField(default='SHORT FILM / 9:16', max_length=80)),
                ('work_empty_message', models.CharField(default='New work is coming soon.', max_length=160)),
                ('process_marquee', models.CharField(default='PROCESS / PROCESS / PROCESS / PROCESS /', max_length=240)),
                ('process_index', models.CharField(default='03 / THE METHOD', max_length=80)),
                ('process_title_1', models.CharField(default='CHAOS IN.', max_length=80)),
                ('process_title_2', models.CharField(default='CLARITY OUT.', max_length=80)),
                ('process_intro', models.TextField(default='Every good edit starts with one question: what does the audience need to feel next?', max_length=400)),
                ('process_1_title', models.CharField(default='DIG', max_length=80)),
                ('process_1_description', models.TextField(default='I find the point, the tension, and the human truth inside the raw material.', max_length=320)),
                ('process_2_title', models.CharField(default='SHAPE', max_length=80)),
                ('process_2_description', models.TextField(default='I build the structure, rhythm, and visual logic before polishing a single frame.', max_length=320)),
                ('process_3_title', models.CharField(default='MOVE', max_length=80)),
                ('process_3_description', models.TextField(default='Typography, motion, sound, and pacing turn the idea into an experience.', max_length=320)),
                ('process_4_title', models.CharField(default='DELIVER', max_length=80)),
                ('process_4_description', models.TextField(default='Every format is checked, finished, and ready to work wherever it lands.', max_length=320)),
                ('about_stamp', models.CharField(default='STORY FIRST\nEVERY FRAME\nSTORY FIRST', max_length=160)),
                ('about_index', models.CharField(default='04 / ABOUT THE EDITOR', max_length=80)),
                ('about_title_1', models.CharField(default='NOT JUST', max_length=80)),
                ('about_title_2', models.CharField(default='PRETTY FRAMES.', max_length=100)),
                ('about_paragraph_1', models.TextField(default='I’m a video editor and motion designer obsessed with the moment a complicated idea suddenly feels simple.', max_length=500)),
                ('about_paragraph_2', models.TextField(default='My work blends documentary instinct, editorial discipline, and bold graphic systems—always in service of the story.', max_length=500)),
                ('stat_1_value', models.CharField(default='06+', max_length=40)),
                ('stat_1_label', models.CharField(default='YEARS CUTTING STORIES', max_length=100)),
                ('stat_2_value', models.CharField(default='120', max_length=40)),
                ('stat_2_label', models.CharField(default='PROJECTS DELIVERED', max_length=100)),
                ('stat_3_value', models.CharField(default='14M', max_length=40)),
                ('stat_3_label', models.CharField(default='ORGANIC VIEWS', max_length=100)),
                ('contact_index', models.CharField(default='05 / START A PROJECT', max_length=80)),
                ('contact_title_1', models.CharField(default='BOOK', max_length=80)),
                ('contact_title_2', models.CharField(default='A CALL.', max_length=80)),
                ('contact_intro', models.TextField(default='Tell me about your project and I’ll get back to you within 24 hours.', max_length=320)),
                ('availability_text', models.CharField(default='CURRENTLY BOOKING / SEP—OCT', max_length=120)),
                ('form_eyebrow', models.CharField(default='PROJECT INTAKE / 2026', max_length=100)),
                ('form_heading', models.CharField(default="LET'S MAKE\nSOMETHING MATTER.", max_length=160)),
                ('form_name_label', models.CharField(default='YOUR NAME *', max_length=80)),
                ('form_name_placeholder', models.CharField(default='Name / studio', max_length=120)),
                ('form_email_label', models.CharField(default='EMAIL ADDRESS *', max_length=80)),
                ('form_email_placeholder', models.CharField(default='you@company.com', max_length=120)),
                ('form_message_label', models.CharField(default='PROJECT DESCRIPTION *', max_length=80)),
                ('form_message_placeholder', models.CharField(default='What are we making, for whom, and when?', max_length=200)),
                ('form_submit_label', models.CharField(default='SUBMIT PROJECT', max_length=80)),
                ('form_validation_message', models.CharField(default='CHECK THE REQUIRED FIELDS.', max_length=160)),
                ('form_sending_message', models.CharField(default='SENDING...', max_length=80)),
                ('form_error_message', models.CharField(default='Something went wrong.', max_length=160)),
                ('response_required_message', models.CharField(default='Please complete all required fields.', max_length=180)),
                ('response_email_message', models.CharField(default='Please enter a valid email address.', max_length=180)),
                ('response_short_message', models.CharField(default='Tell me a little more about your project.', max_length=180)),
                ('response_success_message', models.CharField(default='Message received. I’ll reply within 24 hours.', max_length=180)),
                ('footer_tagline', models.CharField(default='VIDEO EDITOR & MOTION DESIGNER\nAVAILABLE WORLDWIDE', max_length=180)),
                ('footer_email', models.EmailField(default='hello@voxeditor.com', max_length=254)),
                ('footer_link_1_label', models.CharField(default='YOUTUBE', max_length=80)),
                ('footer_link_1_url', models.CharField(default='#work', max_length=500)),
                ('footer_link_2_label', models.CharField(default='INSTAGRAM', max_length=80)),
                ('footer_link_2_url', models.CharField(default='#work', max_length=500)),
                ('copyright_text', models.CharField(default='VOX STUDIO', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'site content',
                'verbose_name_plural': 'site content',
            },
        ),
        migrations.RunPython(create_site_content, remove_site_content),
        migrations.RemoveField(
            model_name='contactmessage',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='project_type',
        ),
    ]
